apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: ghcr.io/tavoa2/clubscope-platform/products-service:af4aaf8
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_HOST
              value: "postgres"
          envFrom:
            - secretRef:
                name: postgres-credentials
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
